### ISSUE TITLE
How to add new foods to the drinkable ones

### ISSUE THREAD

**Issue by Crystal-Spider** [Nova-Committee/DrinkIt#3]
Hi, I know it's written on the webpage, but I do not know enough to actually do it.
Other mods have a config file, but I can't find a config file for this mod, so I'm supposing I'm missing a piece of knowledge on how to do it.
I have a few modded foods I'd like to add to the drinkable ones, how do I exactly do it so that when exporting the modpack they are already set?
Thanks in advance.

**Comment by VulpesStella** [comment]
Sorry for the late reply...
The drinkable foods are stored in an "[item tag](https://minecraft.fandom.com/wiki/Tag?so=search#Item_tags)".
The easiest way to modify it is by directly modifying mod.jar/data/drinkit/tags/items/drinkable.json.
Or use KubeJS / CraftTweaker.

**Comment by Crystal-Spider** [comment]
Do you think you could add a configuration option to do that?
Actually like two options, two lists of item ids, that then you would read and add to your default ones via Java?

**Comment by VulpesStella** [comment]
> Do you think you could add a configuration option to do that? Actually like two options, two lists of item ids, that then you would read and add to your default ones via Java?

Yes. But now I'm busy dealing with Teacon(can be seen as our local ModJam), so it may take some time😂

**Comment by Crystal-Spider** [comment]
Okay, thank you, no problem in waiting!

**Comment by VulpesStella** [comment]
Finally I remembered the issue, let's make it🤣

**Comment by VulpesStella** [comment]
I tried to implement the stuff in [DrinkIt-Forge-1.16.5-1.0.2](https://www.curseforge.com/minecraft/mc-mods/drink-it-forge/files/3975006), and now you can add new foods to the drinkable ones by adding their registry name to the corresponding string list in ".minecraft/config/drinkit-common.toml". I'm not sure whether it's what you wanted. If yes, please tell me and I'll port it to other versions😂

**Comment by Crystal-Spider** [comment]
Yep, that's exactly it, thank you!

**Comment by VulpesStella** [comment]
Wilco, ur welcome :DDD
